after-login-command = []
after-startup-command = ["exec-and-forget sketchybar", "exec-and-forget borders active_color=0xb0ffffff width=8.0"]
exec-on-workspace-change = ["/bin/sh", "-c", "sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE"]
on-focus-changed = ["exec-and-forget sketchybar --trigger aerospace_workspace_change"]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"

[key-mapping]
preset = "qwerty"

[gaps.inner]
horizontal = 12
vertical = 12

[gaps.outer]
left = 12
bottom = 12
top = 46
right = 12

[mode.main.binding]
cmd-ctrl-alt-shift-r = "reload-config"
cmd-ctrl-alt-shift-c = "exec-and-forget\n  padding=12\n  left=$(tomlq \".gaps.outer.left\" $HOME/.aerospace.toml)\n  if [ $left -eq 12 ]; then\n    screen_width=$(displayplacer list | grep -i resolution: | cut -d ' ' -f 2 | cut -d 'x' -f 1)\n    padding=$((screen_width / 5))\n  fi\n  tomlq -i -t \".gaps.outer.left=$padding\" $HOME/.aerospace.toml\n  tomlq -i -t \".gaps.outer.right=$padding\" $HOME/.aerospace.toml\n  aerospace reload-config\n"
cmd-ctrl-alt-shift-h = "focus left"
cmd-ctrl-alt-shift-j = "focus down"
cmd-ctrl-alt-shift-k = "focus up"
cmd-ctrl-alt-shift-l = "focus right"
cmd-ctrl-alt-shift-p = "layout floating tiling"
cmd-ctrl-alt-shift-f = "fullscreen"
cmd-ctrl-alt-shift-left = "move left"
cmd-ctrl-alt-shift-down = "move down"
cmd-ctrl-alt-shift-up = "move up"
cmd-ctrl-alt-shift-right = "move right"
cmd-ctrl-alt-shift-t = "workspace-back-and-forth"
cmd-ctrl-alt-shift-q = "workspace prev --wrap-around"
cmd-ctrl-alt-shift-w = "workspace next --wrap-around"
cmd-ctrl-alt-shift-x = "close-all-windows-but-current"
cmd-ctrl-alt-shift-1 = "workspace 1"
cmd-ctrl-alt-shift-2 = "workspace 2"
cmd-ctrl-alt-shift-3 = "workspace 3"
cmd-ctrl-alt-shift-4 = "workspace 4"
cmd-ctrl-alt-shift-5 = "workspace 5"
alt-shift-w = ["move-node-to-workspace next --wrap-around", "workspace next"]
alt-shift-q = ["move-node-to-workspace prev --wrap-around", "workspace prev"]
alt-shift-1 = ["move-node-to-workspace 1", "workspace 1"]
alt-shift-2 = ["move-node-to-workspace 2", "workspace 2"]
alt-shift-3 = ["move-node-to-workspace 3", "workspace 3"]
alt-shift-4 = ["move-node-to-workspace 4", "workspace 4"]
alt-shift-5 = ["move-node-to-workspace 5", "workspace 5"]
